import type { Metadata } from "next";
import '@/styles/globals.css';
import '@/styles/colors.css';
import '@/styles/fonts.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR" data-theme="light">
      <body>{children}</body>
    </html>
  );
}